### ISSUE TITLE
Requirements.txt

### ISSUE THREAD

**Issue by j0k** [KonstToIT/train_neural_network_app#1]
I follow through README.txt step by step and get `ModuleNotFoundError: No module named 'PySimpleGUI'`. Please, it's better to put all specific packages into requirements.txt (like https://learnpython.com/blog/python-requirements-file/) and add `pip install -r requirements.txt` into intro readme.

**Comment by KonstToIT** [comment]
Thanks for your feedback. I have added `pip install -r requirements.txt` into intro readme.

**Comment by j0k** [comment]
Thanks
